"""
② conductor-discriminant for L/Q_2, G = D4, filtration |G_i| = 8,8,4,4,2,2,2,2,1.
Artin conductor:  a(chi) = sum_{i>=0} (1/[G_0:G_i]) * codim(V^{G_i}).
Conductor-discriminant:  d(L/K) = sum_chi chi(1) * a(chi).
Self-checks: trivial char -> 0; all a(chi) non-negative integers; sum = 24.
"""
from fractions import Fraction as F
import itertools
# ---- D4: elements (i,j) = sigma^i tau^j, i mod 4, j mod 2 ; tau sigma = sigma^{-1} tau ----
def mul(a,b):
    i,j=a; k,l=b
    # (s^i t^j)(s^k t^l) : move t^j past s^k  ->  t^j s^k = s^{(-1)^j k} t^j
    kk = k if j==0 else (-k)%4
    return ((i+kk)%4, (j+l)%2)
def inv(a):
    for b in ELEMS:
        if mul(a,b)==(0,0): return b
ELEMS=[(i,j) for i in range(4) for j in range(2)]
E=[(i,j) for i in range(4) for j in range(2)]
def gen(sub):   # subgroup generated by a set
    S={(0,0)}; fr=[(0,0)]
    while fr:
        x=fr.pop()
        for g in sub:
            y=mul(x,g)
            if y not in S: S.add(y); fr.append(y)
    return frozenset(S)
sig=(1,0); tau=(0,1)
G=gen([sig,tau])
C4=gen([sig])                      # {1,s,s2,s3}
C2=gen([mul(sig,sig)])             # {1,s2}
FILT=[G,G,C4,C4,C2,C2,C2,C2,gen([])]
print("="*84); print("② conductor-discriminant for L/Q_2  (G = D4)"); print("="*84)
print(f"  filtration |G_i| (i=0..8) = {[len(g) for g in FILT]}")
print(f"  sanity: |G|={len(G)}, subgroups nested: {'YES' if all(FILT[i+1]<=FILT[i] for i in range(8)) else 'NO'}")
# ---- the 5 irreducible characters ----
def lin_char(a,b):    # chi(sigma)=(-1)^a, chi(tau)=(-1)^b  (chi(sigma^2)=1 automatically)
    def chi(g):
        i,j=g
        return ((-1)**a)**i * ((-1)**b)**j
    return chi
LINEARS=[lin_char(a,b) for a in (0,1) for b in (0,1)]
# 2-dim rep: sigma -> R, tau -> S
R=[[0,-1],[1,0]]; S=[[1,0],[0,-1]]
def mat2(g):
    i,j=g
    M=[[1,0],[0,1]]
    for _ in range(i): M=mm2(M,R)
    if j: M=mm2(M,S)
    return M
def mm2(A,B):
    return [[sum(A[i][t]*B[t][j] for t in range(2)) for j in range(2)] for i in range(2)]
def fixed_dim_2(Ms):
    """dim of the common fixed space of a list of 2x2 matrices (exact, via rank of P-I)"""
    n=len(Ms); P=[[F(0)]*2 for _ in range(2)]
    for M in Ms:
        for i in range(2):
            for j in range(2): P[i][j]+=F(M[i][j],n)
    # fixed space = ker(P - I)
    A=[[P[i][j]-(1 if i==j else 0) for j in range(2)] for i in range(2)]
    # rank
    r=0
    if any(A[0][j]!=0 for j in range(2)) or any(A[1][j]!=0 for j in range(2)):
        piv=None
        for j in range(2):
            if A[0][j]!=0: piv=j; break
        if piv is None:
            r=1
        else:
            if A[1][0]*A[0][1]-A[1][1]*A[0][0]!=0: r=2
            else: r=1
    return 2-r
def artin_conductor(chi, dim, V_or_fixed):
    """a(chi) = sum_i (1/[G_0:G_i]) * codim(V^{G_i})"""
    tot=F(0)
    for i,Gi in enumerate(FILT):
        if dim==1:
            inv = 1 if chi((0,0))==1 and all(chi(g)==1 for g in Gi) else 0
            cod = 1-inv
        else:
            fdim = V_or_fixed(Gi); cod = 2-fdim
        tot += F(cod, len(G)//len(Gi))
    return tot
def artin_2dim(Gi):
    return fixed_dim_2([mat2(g) for g in Gi])
print()
print("  Artin conductors of the 5 irreducible characters:")
tot=F(0); rows=[]
for a in (0,1):
    for b in (0,1):
        chi=lin_char(a,b)
        ac=artin_conductor(chi,1,None)
        rows.append((f"linear (a={a},b={b})",1,ac)); tot+=1*ac
ac2=artin_conductor(None,2,artin_2dim)
rows.append(("2-dim (standard)",2,ac2)); tot+=2*ac2
for name,dim,ac in rows:
    print(f"    {name:>20} (dim {dim}):  a(chi) = {ac}")
print()
print(f"  ==> sum_chi chi(1)*a(chi) = {tot}        (d(L/Q_2) = 24 from the filtration route)")
print(f"  ==> SELF-CHECK PASS: {tot==24}")
print()
print("="*84); print("correspondence: tower  (2*11 + 2)  vs  characters  (2 + 3 + 3 + 2*8)"); print("="*84)
print(f"""   the three nontrivial LINEAR characters have conductors:
        a = {{ {', '.join(str(int(ac)) for _,d,ac in rows if d==1 and ac!=0)} }}  = the different exponents of the
        three ramified quadratic subfields Q_2(i) [d=2], Q_2(sqrt2) [d=3], Q_2(sqrt(-2)) [d=3]  <-- check below
   the 2-dim character contributes 2*a = 2*{int(ac2)} = {2*int(ac2)}
   and  d(K') = 11 = (one quadratic conductor) + (2-dim conductor) = 3 + 8 : the quartic non-Galois K' sits
        inside the 2-dim piece together with one quadratic piece.""")
# independent check of the quadratic subfields' different exponents via the conductor formula on G/ker
print()
print("  independent check of the three quadratic conductors (via the order-4 subgroups):")
for H in [gen([sig]), gen([mul(sig,sig),tau]), gen([mul(sig,sig),mul(sig,tau)])]:
    # linear character with kernel H
    def chi_H(g,HH=H):
        return 1 if g in HH else -1
    ac=artin_conductor(chi_H,1,None)
    print(f"    H = {sorted(H)}  (index {len(G)//len(H)})  ->  a(chi_H) = {ac}")
# induced character check: a(Ind_H^G 1) = different exponent of the subfield fixed by H
print()
print("  induced-character route for the QUARTIC subfield K' = Q_2(2^(1/4)) (H = an order-2 subgroup):")
for inv_el in [mul(sig,sig), tau, mul(sig,tau), mul(mul(sig,sig),tau), mul(mul(mul(sig,sig),sig),tau)]:
    H=gen([inv_el])
    # permutation rep of G on G/H ; fixed dim of G_i = number of G_i-orbits
    cosets=[]
    seen=set()
    for g in G:
        c=frozenset(mul(g,h) for h in H)
        if c not in seen: seen.add(c); cosets.append(c)
    tot2=F(0)
    for i,Gi in enumerate(FILT):
        # orbits of Gi acting on cosets by left multiplication
        parent={c:c for c in cosets}
        def find(x):
            while parent[x]!=x: x=parent[x]
            return x
        for c in cosets:
            for g in Gi:
                d=frozenset(mul(g,x) for x in c)
                ra,rb=find(c),find(d)
                if ra!=rb: parent[ra]=rb
        norb=len({find(c) for c in cosets})
        tot2+=F(len(cosets)-norb, len(G)//len(Gi))
    note = "<-- matches d(K')=11" if tot2==11 else ""
    print(f"    H=<{inv_el}>  a(Ind 1_H) = {tot2}   {note}")
