"""Robust index computation: [Z^8 : L] = gcd of all 8x8 minors of a basis (cleared denominators)."""
from fractions import Fraction as F
import itertools
def mul4(u,v):
    raw=[0]*7
    for i,a in enumerate(u):
        for j,b in enumerate(v): raw[i+j]+=a*b
    for k in range(6,3,-1):
        c=raw[k]
        if c: raw[k]-=c; raw[k-4]+=2*c
    return tuple(raw[:4])
def add4(u,v): return tuple(a+b for a,b in zip(u,v))
def sub4(u,v): return tuple(a-b for a,b in zip(u,v))
def Lmul(x,y):
    u,v=x; u2,v2=y
    return (sub4(mul4(u,u2),mul4(v,v2)), add4(mul4(u,v2),mul4(v,u2)))
BAS=[]
for j in range(8):
    b=[0]*4; b[j%4]=1
    BAS.append((tuple(b),(0,0,0,0)) if j<4 else ((0,0,0,0),tuple(b)))
def coords(x): return tuple(x[0])+tuple(x[1])
def vec2el(v): return (tuple(v[0:4]),tuple(v[4:8]))
def mm(A,B):
    n=len(A); return [[sum(A[i][t]*B[t][j] for t in range(n)) for j in range(n)] for i in range(n)]
def mult_matrix(v):
    x=vec2el(v); cols=[coords(Lmul(x,BAS[j])) for j in range(8)]
    return [[cols[j][i] for j in range(8)] for i in range(8)]
def is_integral(v):
    M=mult_matrix(v); n=8
    P=[[F(1) if i==j else F(0) for j in range(n)] for i in range(n)]
    p=[]
    for k in range(1,n+1):
        P=mm(P,M); p.append(sum(P[i][i] for i in range(n)))
    e=[]
    for k in range(1,n+1):
        acc=F(0)
        for j in range(1,k+1):
            ej=F(1) if (k-j)==0 else e[k-j-1]
            acc+=((-1)**(j-1))*ej*p[j-1]
        e.append(acc/k)
    c=[F(1)]+[((-1)**k)*e[k-1] for k in range(1,n+1)]
    return all(x.denominator==1 for x in c)
def det(M):
    n=len(M); s=F(0)
    for pm in itertools.permutations(range(n)):
        sg=1
        for i in range(n):
            for j in range(i+1,n):
                if pm[i]>pm[j]: sg=-sg
        t=F(sg)
        for i in range(n): t*=M[i][pm[i]]
        s+=t
    return s
def lattice_index(basis_frac):
    """basis_frac: 8 vectors (Fractions). index [Z^8 : lattice] = gcd of minors after clearing denom."""
    d=1
    for v in basis_frac:
        for x in v: d=d*x.denominator//__import__('math').gcd(d,x.denominator)
    Mi=[[int(F(x)*d) for x in v] for v in basis_frac]
    g=0
    for sub in itertools.combinations(range(8),8):
        Mx=[[Mi[i][j] for j in range(8)] for i in sub]
        dd=int(det(Mx)); g=__import__('math').gcd(g,abs(dd))
    return F(g, d**8)
print("="*80); print("index [O_L : Z[delta,i]] -- computed as gcd of 8x8 minors"); print("="*80)
basis=[list(coords(b)) for b in BAS]
# relative index of any lattice vs Z^8 == its own index (start: Z^8, index 1)
for rnd in range(1,8):
    found=[]
    for mask in range(1,256):
        v=[F(0)]*8
        for j in range(8):
            if (mask>>j)&1:
                for i in range(8): v[i]+=F(1,2)*F(basis[j][i])
        if all(x.denominator==1 for x in v): continue
        if is_integral(v): found.append(v)
    if not found:
        print(f"  round {rnd}: no new integral half-elements -> STABLE"); break
    # enlarge: lattice generated by current basis + found elements (scale by 2 to keep integers)
    rows=[[2*F(x) for x in basis[j]] for j in range(8)]+[[2*F(x) for x in f] for f in found]
    # extract a basis of the generated lattice via integer HNF-free method: use math.gcd of minors on subsets
    # simpler: take the lattice generated by these rows; its basis = the rows after integer row reduction.
    # We instead recompute the *index* of the new lattice w.r.t. Z^8 directly by finding a basis:
    # choose 8 rows spanning, then adjust: use successive minima via integer row operations (Bareiss on 15x8).
    import math
    # integer row-echelon reduction
    M=[row[:] for row in rows]; R=len(M); n=8; r=0
    for c in range(n):
        idxs=[i for i in range(r,R) if M[i][c]!=0]
        if not idxs: continue
        while True:
            idxs=[i for i in range(r,R) if M[i][c]!=0]
            if not idxs: break
            i0=min(idxs,key=lambda i:abs(M[i][c])); M[r],M[i0]=M[i0],M[r]
            ch=False
            for i in range(R):
                if i!=r and M[i][c]!=0:
                    q=M[i][c]//M[r][c]
                    if q:
                        M[i]=[M[i][j]-q*M[r][j] for j in range(n)]; ch=True
            if not ch: break
        r+=1
        if r==R: break
    newb=[[F(M[i][j],2) for j in range(n)] for i in range(8)]
    basis=newb
    print(f"  round {rnd}: {len(found)} integral half-elements; lattice enlarged")
fin=lattice_index(basis)
print(f"\n  index [O_L : Z[delta,i]] = {fin}")
print(f"  |D_L| = 2^30 / index^2 = {'2^'+str(30-2*int(fin).bit_length()+ (0 if fin&(fin-1)==0 else 0)) if False else '2^30/'+str(int(fin)**2)}")
if fin.denominator==1:
    i=int(fin); k=i.bit_length()-1
    if i==2**k:
        print(f"  ==> index = 2^{k}  =>  |D_L| = 2^{30-2*k}  =>  d(L/Q_2) = {30-2*k}")
